name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Build
      with: 
        uses: cd aoc_208 && cargo build --verbose
    - uses: actions/checkout@v2
      name: Run tests
      with: 
        uses: cd aoc_208 && cargo test --verbose
